export const usernames = [
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Andriy Sabat",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Volodymyr Zhyvan",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Всратослав",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andriy Sabat",
    "Ihor Tanchyn",
    "Всратослав",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andriy Sabat",
    "Bohdan Smachylo",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andriy Sabat",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Всратослав",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andriy Sabat",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Всратослав",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Всратослав",
    "Mykola Klymenko",
    "Всратослав",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Всратослав",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Всратослав",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykhailo Pylyp",
    "Ihor Tanchyn",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andriy Sabat",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Volodymyr Zhyvan",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Volodymyr Zhyvan",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Andrii Yevchak",
    "Andriy Sabat",
    "Bohdan Smachylo",
    "Andriy Sabat",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Всратослав",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Volodymyr Zhyvan",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Всратослав",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Всратослав",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Всратослав",
    "Andrii Yevchak",
    "Всратослав",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Всратослав",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Volodymyr Zhyvan",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Sviatoslav",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Volodymyr Zhyvan",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykhailo Pylyp",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Mykhailo Pylyp",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andriy Sabat",
    "Andrii Yevchak",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Mykhailo Pylyp",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykhailo Pylyp",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Volodymyr Zhyvan",
    "Andrii Yevchak",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Volodymyr Zhyvan",
    "Andriy Sabat",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Volodymyr Zhyvan",
    "Volodymyr Zhyvan",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Ihor Tanchyn",
    "Volodymyr Zhyvan",
    "Ihor Tanchyn",
    "Віталій Маковейчук",
    "Andriy Sabat",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Andriy Sabat",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Sviatoslav",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Andriy Sabat",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Volodymyr Zhyvan",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Sviatoslav",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andriy Sabat",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Andriy Sabat",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Sviatoslav",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Sviatoslav",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Bohdan Smachylo",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Sviatoslav",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Ihor Tanchyn",
    "Andrii Yevchak",
    "Bohdan Smachylo",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Mykola Klymenko",
    "Sviatoslav",
    "Andrii Yevchak",
    "Sviatoslav",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Andrii Yevchak",
    "Andrii Yevchak",
    "Mykola Klymenko",
    "Mykola Klymenko",
    "Bohdan Smachylo",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Sviatoslav",
    "Віталій Маковейчук",
    "Mykola Klymenko",
    "Віталій Маковейчук"
]